ncdac_opi_analytics:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: "{{ env_var('DATABASE_ANALYTICS') }}"
      extensions:
        - sqlite
      attach:
        - path: "{{ env_var('DATABASE_SOURCE') }}"
          type: sqlite
      threads: 1
